### ISSUE TITLE
Make it work for multiple domain server

### ISSUE THREAD

**Issue by teutat3s** [afterlogic/aurora-module-change-password-in-mail-server-database-plugin#1]
Dear devs,

thank you for this nice piece of software. We would like to try out afterlogic webmail-lite-8 on our multi-domain mailserver. As far as I can see it now, this module allows changing passwords if there are no duplicate usernames in the mysql database. 
Could you please give me a hint on how to extract the domain from the currently logged-in user Account, to pass that to the sql command, too? I'm thinking of something like:
```
$sql = "UPDATE mailbox SET password='".$sPasshash."' WHERE username='".$oAccount->IncomingLogin."' AND domain='".$oAccount->Domain"'";
```
Though I could only see `email` in the API documentation. Or would I have to supply an external script (bash) and extract that domain information manually?

**Comment by afterlogic-support** [comment]
Typically, IncomingLogin property contains full email address, unless you have "Use full email address as login" option un-checked for specific email server in the product config. 
Still, there's also Email property, and you can obtain domain from it like this:
`list($sLogin, $sDomainName) = explode('@', $oAccount->Email);`
Hope this helps.
