### ISSUE TITLE
UI Error: Can't save new password

### ISSUE THREAD

**Issue by teutat3s** [afterlogic/aurora-module-change-password-in-mail-server-database-plugin#2]
I managed to get this working, thanks to your help, but after getting the SQL query to work I still get this UI error:

![webmail-error](https://user-images.githubusercontent.com/10206665/55915683-7383c080-5bea-11e9-9e08-ea384642706f.jpg)

The query is executed successfully, I can logout and login only with the new password. But the UI doesn't respond like expected, it leaves the "Change password" pop-up open and shows the mentioned error.

What I changed in Modules.php is:

```
$mysqlcon=mysqli_connect($config_dbhost, $config_dbuser, $config_dbpass, $config_dbname);
                        if($mysqlcon){
                                $sPasshash = exec("doveadm pw -s 'SHA512-CRYPT' -p '".$sPassword."'");
                                list($sLogin, $sDomainName) = explode('@', $oAccount->Email);
                                $sql = "UPDATE mailbox SET password = '".$sPasshash."' WHERE username = '".$sLogin."' AND domain = '".$sDomainName."'";
                                $bResult = mysqli_query($mysqlcon,$sql) or trigger_error(mysqli_error($mysqlcon)." ".$sql);
                                if (!$bResult){
                                        throw new \Aurora\System\Exceptions\ApiException(\Aurora\System\Exceptions\Errs::UserManager_AccountNewPasswordUpdateError);
                                }
                                mysqli_close($mysqlcon);
```

In the HTTP POST answer I see:
```
{"AuthenticatedUserId":4,"@Time":0.09297513961791992,"Module":"Mail","Method":"ChangePassword","Result":false,"SubscriptionsResult":null}
```

the logs just show:
```
[21:38:17.82][60c25724] API: Mail::ChangePassword^M
[21:38:17.82][60c25724] Execute subscription: ChangePasswordInMailServerDatabasePlugin::onBeforeChangePassword^M
[21:38:17.87][60c25724] Execute subscription: Core::onAfterChangePassword^M
```

I guess this is not the intended behaviour, how can I help debug this further?

**Comment by afterlogic-support** [comment]
There were recent changes in the framework, regarding password change functionality - but this specific plugin wasn't adjusted in that regard for some reason. Developers are looking into this; will let you know once there are news. Thanks.

**Comment by afterlogic-support** [comment]
The module has been updated, hope the new version works for you. Thanks again!

**Comment by teutat3s** [comment]
thanks, works great here.
